# Generated by Django 3.0.5 on 2020-04-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('email', models.CharField(max_length=50)),
                ('sqfeet', models.IntegerField()),
            ],
        ),
    ]
