# Generated by Django 3.0.5 on 2020-04-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='sqfeet',
        ),
        migrations.AddField(
            model_name='quote',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='quote',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='zipcode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='quote',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
