# Generated by Django 3.0.5 on 2020-05-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0003_quote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
